version: "3"
services:
  gradle:
    image: gradle:jdk9
    volumes:
      - .:/home/gradle/project
    working_dir: /home/gradle/project
    command: gradle run
    links:
      - "fluentd"

  fluentd:
    build: ./fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "redis"

  redis:
    build: ./redis
    restart: always
    expose:
      - 6379
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    command: redis-server --appendonly yes
